(cl:in-package wit_node-msg)
(cl:export '(HEADER-VAL
          HEADER
          TIME-VAL
          TIME
          ACC-VAL
          ACC
          GYRO-VAL
          GYRO
          RPY-VAL
          RPY
          MAG-VAL
          MAG
          PS-VAL
          PS
          TEMPERATURE-VAL
          TEMPERATURE
          ALTITUDE-VAL
          ALTITUDE
          AP-VAL
          AP
          LATITUDE-VAL
          LATITUDE
          LONGTITUDE-VAL
          LONGTITUDE
          GPSH-VAL
          GPSH
          GPSY-VAL
          GPSY
          GPSV-VAL
          GPSV
          QUARTERNION-VAL
          QUARTERNION
          SN-VAL
          SN
          DOP-VAL
          DOP
))